

## 创建目录
**fsPromises.mkdir(path[, options])**
- options \<Object\> | \<integer\>
   - recursive \<boolean\> 默认值: false。
   - mode \<integer\> Windows 上不支持。默认值: 0o777。
- callback \<Function\>
   - err \<Error\>

<pre>
const fs = require('fs')
let pathDir: string = dirGrandfather

<b>fs.promises.mkdir(pathDir, {recursive: true})</b>
    .catch((err: object) => {
        console.log(err);
    })
</pre>

<br/>

## 删除目录(注意, 只能删除空目录, 即里面不能有文件或子目录存在)
**fsPromises.rmdir(path)**    
回调函数中只有一个err参数
<pre>
<b>fs.promises.rmdir('./dirEmpty')</b> //删除dirEmpty这个空目录
    .catch((err: object) => {
        console.log(err);
    })
</pre>


<br/>

## 判断目录或文件是否存在
**fsPromises.stat(path[, options])**
 回调有两个参数 (err, stats)，其中 stats 是 fs.Stats。  
 
<pre>
const fs = require('fs')
const path = require('path')

let pathDir = path.join(__dirname, './dirTest2')  //要判断是否存在的目录或文件

<b>fs.promises.stat(pathDir)</b>
    .then((<b>objStats</b>: object) => {
        console.log(`存在 --> ${pathDir}`);
    })
    .catch((err: object) => {
        console.log(`不存在--> ${pathDir}`);

    })
</pre>  
 

 **注意: 不建议在调用 fs.open()、 fs.readFile() 或 fs.writeFile() 之前使用 fs.stat() 检查文件是否存在。 而是应该直接打开、读取或写入文件**，如果文件不可用则处理引发的错误。   
 要检查文件是否存在, 但随后并不对其进行操作，则建议使用 fs.access()。

<br/>

## 读取目录中的内容(不包括子目录中的内容)
**fsPromises.readdir(path[, options])**  
回调函数有两个参数 (err, arrFiles)，其中 arrFiles 是目录中的文件名的**数组**（不包括 '.' 和 '..'）。 

<pre>
const fs = require('fs')
const path = require('path')

<b>fs.promises.readdir(path.join(__dirname, 'dirGrandfather'))</b>
    .then((arrFileName: string[]) => {
        console.log(arrFileName); //这个数组,只包括dirGrandfather目录中的文件名和子目录名, 而不包括该子目录中的内容.
    })
    .catch((err: object) => {
        console.log(err);
    })
</pre>


<br/>

## 重命名(或移动) 目录(或文件)
**fsPromises.rename(oldPath, newPath)**
回调函数只有一个err参数.  
并且, 被移动的目录, 就算里面有文件和子目录, 也没关系, 照样能被整体移动到新路径中.

<pre>
const fs = require('fs')
const path = require('path')

let pathDir = path.join(__dirname, './dirGrandfather')

//将dirGrandfather目录,移动到newDir目录下
<b>fs.promises.rename(pathDir, './newDir')</b>
    .catch((err: object) => {
        console.log(err);
    })
</pre>
